name: pandera-presentations
channels:
  - conda-forge
dependencies:
  - dask
  - hypothesis
  - matplotlib
  - modin==0.17.0
  - modin-core==0.17.0
  - modin-dask==0.17.0
  - multimethod
  - pandas
  - pandas-profiling
  - pandera
  - pyjanitor
  - pyspark==3.3.1
  - pytest
  - requests
  - seaborn
  - scikit-learn
  - scipy
  - statsmodels
  - pip:
    - ray
