name: pandera-presentations
channels:
  - conda-forge
dependencies:
  - hypothesis
  - matplotlib
  - pandas
  - pandas-profiling
  - pandera
  - pyjanitor
  - pytest
  - requests
  - seaborn
  - scikit-learn
  - statsmodels
